import java.util.Scanner;
import javax.swing.*;
import java.io.*;
import java.text.NumberFormat;
import java.util.Random;

/** ***************************************************
 *  Name:           your name
 *  Class:          CS20S
 * 
 *  Assignment:     Simple while loop example
 *  
 *                  count and add numbers until a
 *                  0 is generated by the random number 
 *                  generator
 *                  
 *                  adding a quit/continue loop to give the
 *                  option to add more than one list of numbers
 * 
 *************************************************************/

public class CS20SCountingExampleWithQuitContinue {

    public static void main(String[] args) throws IOException{
        // ***** constants *******

        // ***** variables *****

        String banner = "";             // output banner
        String prompt = "";             // prompt for user input
        String qcPrompt = "";           // quite or continue?

        String strin = "";              // string fro keyboard input
        String strout = "";             // string for formatted output

        String delim = "[ ]+";          // delimiter for splitting input records
        String[] tokens = null;         // used to split input records

        // a new line character that works on every computer system
        String nl = System.lineSeparator();

        // local variables

        int number = 0;         // number entered from the keyboard    
        int count = 0;          // counter, how many numbers are entered
        int sum = 0;            // sum of the numbers entered

        char qc = 'y';          // choice to quit or continue

        // ***** objects *****

        Scanner scanner = new Scanner(System.in);
        //NumberFormat currency = NumberFormat.getCurrencyInstance();
        Random rnd = new Random();

        // ***** print banners *****

        banner = "*****************************" + nl;
        banner += "Name:        Sveinson" + nl;
        banner += "Class:       CS30S" + nl;
        banner += "Assignment:  simple random number example" + nl;
        banner += "*****************************" + nl + nl;

        System.out.println(banner);
        //fout.print(banner);

        // ***** Get Input *****

        prompt = "random numbers will be generated," + nl;
        prompt += "when a 0 is generated the app will close." + nl;

        qcPrompt = "Do you want to process a list of numbers? y/n";

        // ***** Main Processing *****

        //  q/c pre-loop processing

        System.out.println(qcPrompt);
        strin = scanner.next();
        //System.out.println(qc);
        qc = strin.charAt(0);
        Character.toUpperCase(qc);
        System.out.println(qc);

        while(qc == 'Y'){

            // *** process a list of numbers
            // counting number pre-loop
            count = 0;              // make sure we start counting at 0
            sum = 0;                // make sure we start adding from 0

            System.out.println(prompt);
            number = rnd.nextInt(6);
            //System.out.println(number);

            while(number != 0){
                System.out.println(number);
                // stuff to be repeated goes here
                // iteration counter
                count++;            // count numbers
                sum += number;      // add numbers

                // ** update the control variable **
                //System.out.println("enter another number, 0 to quit");
                number = rnd.nextInt(6);
            }// end while

            // post-loop processing
            System.out.format("Count = %4d%s", count, nl);
            System.out.format("Sum = %4d%s", sum, nl);
            System.out.println("********************" + nl);

            // update qc control
            System.out.println(qcPrompt);
            strin = scanner.next();
            //System.out.println(qc);
            qc = strin.charAt(0);
            Character.toUpperCase(qc);
            //System.out.println(qc);
        }// end qc loop

        // q/c post loop processing

        // ***** Print Formatted Output *****
        // ***** Closing Message *****
        System.out.println();
        System.out.println("end of processing");
        //fout.println("End of Processing");

    } // end main 

} // end FormatTemplate
